// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/views/welcome/welcome_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/views/welcome',
        uri: Uri.parse('/views/welcome'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.WelcomePage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  views: (
    path: '/views',
    welcome: '/views/welcome',
  ),
);
